=== SCHIEPPH/schiepph/Product/Production/XML/HL7Validation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="HL7Validation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ValidHL7Versions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="version" maxOccurs="unbounded">
                                <xs:complexType/>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="severity" type="xs:string" use="required"/>
                        <xs:attribute name="errorMessageId" type="xs:unsignedInt" use="required"/>
                        <xs:attribute name="errorCodeId" type="xs:unsignedInt" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="SupportedAdtMessages">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="adtMessage"/>
                        </xs:sequence>
                        <xs:attribute name="severity" type="xs:string" use="required"/>
                        <xs:attribute name="errorMessageId" type="xs:unsignedInt" use="required"/>
                        <xs:attribute name="errorCodeId" type="xs:unsignedInt" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="RequiredSegments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="segmentName"/>
                        </xs:sequence>
                        <xs:attribute name="severity" type="xs:string" use="required"/>
                        <xs:attribute name="errorMessageId" type="xs:unsignedInt" use="required"/>
                        <xs:attribute name="errorCodeId" type="xs:unsignedInt" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Fields">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Field" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name"/>
                                        <xs:element name="Location" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="hl7Segment">
                                                  <xs:complexType>
                                                  <xs:attribute name="fieldNumber" type="xs:double"
                                                  use="required"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="identifier">
                                                  <xs:complexType>
                                                  <xs:attribute name="fieldNumber" type="xs:double"
                                                  use="required"/>
                                                  <xs:attribute name="mustMatch" type="xs:boolean"
                                                  default="true"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="version" type="xs:string"
                                                  use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description"/>
                                        <xs:element name="Validations">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="usage">
                                                  <xs:complexType>
                                                  <xs:attribute name="severity" type="xs:string"
                                                  use="required"/>
                                                  <xs:attribute name="errorMessageId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="errorCodeId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="cardinality" maxOccurs="1"
                                                  minOccurs="0">
                                                  <xs:complexType>
                                                  <xs:attribute name="severity" type="xs:string"
                                                  use="required"/>
                                                  <xs:attribute name="errorMessageId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="errorCodeId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="dataType" minOccurs="0">
                                                  <xs:complexType>
                                                  <xs:attribute name="severity" type="xs:string"
                                                  use="required"/>
                                                  <xs:attribute name="errorMessageId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="errorCodeId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="format" type="xs:string"/>
                                                  <xs:attribute name="specialCharacters"
                                                  type="xs:string"/>
                                                  <xs:attribute name="minimumLength"
                                                  type="xs:unsignedInt"/>
                                                  <xs:attribute name="maximumLength"
                                                  type="xs:unsignedInt"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="dataRange" minOccurs="0">
                                                  <xs:complexType>
                                                  <xs:attribute name="severity" type="xs:string"
                                                  use="required"/>
                                                  <xs:attribute name="errorMessageId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="errorCodeId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="ValueList" minOccurs="0">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="value" maxOccurs="unbounded"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="severity" type="xs:string"
                                                  use="required"/>
                                                  <xs:attribute name="errorMessageId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="errorCodeId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="caseSensitive"
                                                  type="xs:boolean" default="false"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="RequiresFieldValue">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="fieldValue">
                                                  <xs:complexType> </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  <xs:attribute name="severity" type="xs:string"
                                                  use="required"/>
                                                  <xs:attribute name="errorMessageId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="errorCodeId"
                                                  type="xs:unsignedInt" use="required"/>
                                                  <xs:attribute name="fieldNumber" type="xs:double"
                                                  use="required"/>
                                                  <xs:attribute default="false" name="caseSensetive"
                                                  type="xs:boolean"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="RequiresField">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="conditionalFieldIId">
                                                  <xs:complexType>
                                                  <xs:attribute default="true" name="mustExist"
                                                  type="xs:boolean"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:integer" use="required"/>
                                    <xs:attribute default="false" name="canContainMultipleValues"
                                        type="xs:boolean"/>
                                    <xs:attribute name="repeatingElement" type="xs:string"
                                        default="Field"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ErrorMessages">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="errorMessage" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
                                    <xs:attribute name="printFieldName" type="xs:boolean"
                                        use="required"/>
                                    <xs:attribute name="printFieldValue" type="xs:boolean"
                                        use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ErrorCodes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="errorCode">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DateFormats">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="format"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SCHIEPPH/schiepph/Product/Production/Software/src/test/resources/SyndromicDataValidationsTestConditionalField.xml
<?xml version="1.0" encoding="UTF-8"?>
<HL7Validation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:../../../Product/Production/XML/HL7Validation.xsd">
    <ValidHL7Versions errorCodeId="3" errorMessageId="3" severity="Hold" >
        <version>2.3.1</version>
        <version>2.5.1</version>
    </ValidHL7Versions>
    <SupportedAdtMessages errorCodeId="3" errorMessageId="4" severity="Hold" >
        <adtMessage>A01</adtMessage>
        <adtMessage>A03</adtMessage>
        <adtMessage>A04</adtMessage>
        <adtMessage>A08</adtMessage>
    </SupportedAdtMessages>
    <RequiredSegments severity="Hold" errorMessageId="9" errorCodeId="5">
        <segmentName>MSH</segmentName>
        <segmentName>EVN</segmentName>
        <segmentName>PID</segmentName>
        <segmentName>PV1</segmentName>
        <segmentName>OBX</segmentName>
    </RequiredSegments>
    <Fields>
        <Field id="12">
            <name>Age</name>
            <Location version="2.3.1" >
                <hl7Segment fieldNumber="5.1" >OBX</hl7Segment>
                <identifier fieldNumber="3.1">21612-7</identifier>
            </Location>
            <Location version="2.5.1" >
                <hl7Segment fieldNumber="5.1" >OBX</hl7Segment>
                <identifier mustMatch="true" fieldNumber="3.1">21612-7</identifier>
            </Location>
            <description>Field #11 - Numeric value of patient age </description>
            <Validations>
                <usage errorCodeId="1" errorMessageId="1" severity="Hold" >Optional</usage>
				<dataType errorCodeId="4" errorMessageId="10" severity="Hold">Numeric</dataType>
				<!-- This element defines the secondary field (Field ID 13 - Age Unit) that must be present, and valid, if the current field is present in the HL7 message.  -->
				<RequiresField errorCodeId="11" errorMessageId="11" severity="Hold">
					<conditionalFieldId>13</conditionalFieldId>
				</RequiresField>
            </Validations>
        </Field>
        <Field id="13">
            <name>Age Units</name>
            <Location version="2.3.1" >
                <hl7Segment fieldNumber="6.1" >OBX</hl7Segment>
                <identifier mustMatch="true" fieldNumber="3.1">21612-7</identifier>
            </Location>
            <Location version="2.5.1" >
                <hl7Segment fieldNumber="6.1" >OBX</hl7Segment>
                <identifier mustMatch="true" fieldNumber="3.1">21612-7</identifier>
            </Location>
            <description>Field #12 - Unit corresponding to numeric value of patient age (e.g. Days, Month or Years) </description>
            <Validations>
                <usage errorCodeId="1" errorMessageId="1" severity="Hold" >Conditional</usage>
                <!-- Add valid values with value set code PHVS_AgeUnit_SyndromicSurveillance -->
				<ValueList errorCodeId="3" errorMessageId="5" severity="Hold" >
					<value>d</value>
					<value>mo</value>
					<value>UNK</value>
					<value>wk</value>
					<value>a</value>
				</ValueList>
				<!-- This element defines the value that a secondary field (6.3) must contain if the current field (6.1) is present in the HL7 message. -->
				<RequiresFieldValue errorCodeId="6" errorMessageId="12" severity="Hold" fieldNumber="6.3" >
                    <fieldValue>UCUM</fieldValue>
                </RequiresFieldValue>
				<!-- This element defines the secondary field (5.1 - Age) that must be present, and valid, if the current field is present in the HL7 message.  -->
				<RequiresField errorCodeId="11" errorMessageId="11" severity="Hold">
					<conditionalFieldId>12</conditionalFieldId>
				</RequiresField>
            </Validations>
        </Field>
        <!--<Field id="4">-->
            <!--<name>Facility Location - City</name>-->
            <!--<Location version="2.3.1" >-->
                <!--<hl7Segment fieldNumber="5.6" >OBX</hl7Segment>-->
                <!--<identifier mustMatch="true" fieldNumber="3.1">SS002</identifier>-->
            <!--</Location>-->
            <!--<Location version="2.5.1" >-->
                <!--<hl7Segment fieldNumber="5.6" >OBX</hl7Segment>-->
                <!--<identifier fieldNumber="3.1">SS002</identifier>-->
            <!--</Location>-->
            <!--<description>Field #4 - City of treating facility location</description>-->
            <!--<Validations>-->
                <!--<usage errorCodeId="0" errorMessageId="0" severity="None" >Optional</usage>-->
                <!--<RequiresField errorCodeId="1" errorMessageId="1" severity="Hold" >-->
                    <!--<conditionalFieldId>7</conditionalFieldId>-->
                <!--</RequiresField>-->
            <!--</Validations>-->
        <!--</Field>-->
        <!--<Field id="7">-->
            <!--<name>Facility Location - State</name>-->
            <!--<Location version="2.3.1" >-->
                <!--<hl7Segment fieldNumber="5.7" >OBX</hl7Segment>-->
                <!--<identifier mustMatch="true" fieldNumber="3.1">SS002</identifier>-->
            <!--</Location>-->
            <!--<Location version="2.5.1" >-->
                <!--<hl7Segment fieldNumber="5.7" >OBX</hl7Segment>-->
                <!--<identifier mustMatch="true" fieldNumber="3.1">SS002</identifier>-->
            <!--</Location>-->
            <!--<description>Field #6 - State of treating facility location</description>-->
            <!--<Validations>-->
                <!--<usage errorCodeId="0" errorMessageId="0" severity="None" >Optional</usage>-->
            <!--</Validations>-->
        <!--</Field>-->
    </Fields>
    <ErrorMessages>
        <!-- Error messages are dynamically created by appending one of
            the following messages to the name of the field that is in error.
            Message id 0 is reserved for checks that cannot fail a validity
            check, such as an optional filed being missing (i.e. this is not
            an error, so there is no error message to print) -->
        <errorMessage id="0" printFieldName="false" printFieldValue="false" ></errorMessage>
        <errorMessage id="1" printFieldName="true" printFieldValue="false" >is a required field and is missing.</errorMessage>
        <errorMessage id="2" printFieldName="true" printFieldValue="false" >is a required/empty field and is missing.</errorMessage>
        <errorMessage id="3" printFieldName="false" printFieldValue="true" >is not a supported HL7 version.</errorMessage>
        <errorMessage id="4" printFieldName="false" printFieldValue="true" >is not a supported ADT Message.</errorMessage>
        <errorMessage id="5" printFieldName="true" printFieldValue="true" >is not a valid value.</errorMessage>
        <errorMessage id="6" printFieldName="true" printFieldValue="true" >is not alphabetic.</errorMessage>
        <errorMessage id="7" printFieldName="true" printFieldValue="true" >is not numeric.</errorMessage>
        <errorMessage id="8" printFieldName="true" printFieldValue="true" >is not alpha-numeric.</errorMessage>
        <errorMessage id="9" printFieldName="true" printFieldValue="true" >is a required HL7 message segment and is missing.</errorMessage>
		<errorMessage id="10" printFieldName="true" printFieldValue="true" >is not a valid format.</errorMessage>
		<errorMessage id="11" printFieldName="true" printFieldValue="false" >is dependent upon another field whose definition is not found in the Rule Book.</errorMessage>
        <errorMessage id="12" printFieldName="true" printFieldValue="false" >is a conditionally required field and is missing.</errorMessage>
    </ErrorMessages>
    <ErrorCodes>
        <errorCode id="0"></errorCode>
        <errorCode id="1">SCHIEPPHRequiredFieldMissing</errorCode>
        <errorCode id="2">SCHIEPPHRequiredEmptyFieldMissing</errorCode>
        <errorCode id="3">SCHIEPPHInvalidValue</errorCode>
        <errorCode id="4">SCHIEPPHInvalidFormat</errorCode>
        <errorCode id="5">SCHIEPPHRequiredSegmentMissing</errorCode>
        <errorCode id="6">SCHIEPPHConditionallyRequiredFieldMissing</errorCode>
    </ErrorCodes>
    <DateFormats>
        <format>yyyyMMddHHmm</format>
        <format>yyyyMMddHHmm-zzzz</format>
        <format>yyyyMMddHHmm+zzzz</format>
        <format>yyyyMMddHHmmss</format>
        <format>yyyyMMddHHmmss-zzzz</format>
        <format>yyyyMMddHHmmss+zzzz</format>
        <format>yyyyMMddHHmmss.S</format>
        <format>yyyyMMddHHmmss.S-zzzz</format>
        <format>yyyyMMddHHmmss.S+zzzz</format>
        <format>yyyyMMddHHmmss.SS</format>
        <format>yyyyMMddHHmmss.SS-zzzz</format>
        <format>yyyyMMddHHmmss.SS+zzzz</format>
        <format>yyyyMMddHHmmss.SSS</format>
        <format>yyyyMMddHHmmss.SSS-zzzz</format>
        <format>yyyyMMddHHmmss.SSS+zzzz</format>
    </DateFormats>
</HL7Validation>

=== SCHIEPPH/schiepph/Product/Production/XML/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<HL7Validation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/ralph/work/agilex/SCHIEPPH/Source/schiepph-code/Product/Production/xml/HL7Validation.xsd">
    <ValidVersions>
        <version/>
        <version/>
    </ValidVersions>
    <SupportedAdtMessages>
        <adtMessage>
        </adtMessage>
        <adtMessage>
        </adtMessage>
    </SupportedAdtMessages>
    <Fileds>
        <Field>
            <name>
            </name>
            <Location>
                <hl7Segment/>
            </Location>
            <Location>
                <hl7Segment/>
            </Location>
            <description>
            </description>
            <Validations>
                <usage/>
            </Validations>
        </Field>
        <Field>
            <name>
            </name>
            <Location>
                <hl7Segment/>
            </Location>
            <Location>
                <hl7Segment/>
            </Location>
            <description>
            </description>
            <Validations>
                <usage/>
            </Validations>
        </Field>
    </Fileds>
    <ErrorMessages>
        <errorMessage/>
        <errorMessage/>
    </ErrorMessages>
</HL7Validation>
